# tola.toml

[site.info]
title = "gomazarashi.com"
author = "gomazarashi"
description = "個人サイト（仮）"
language = "ja"
url = "https://gomazarashi.com"

[site.header]
styles = ["assets/styles/site.css"]

[build]
content = "content"
output = "docs"
deps = ["templates", "utils"]
assets.nested = ["assets/styles"]
